#document settings
title: Kit de Dados Abertos
desc: "Kit para implementação de Plano de Dados Abertos"
url: //dadosgovbr.github.io/kit/
repo_name: dadosgovbr.github.io
branch: master

#global settings, no need to change these
root_url: //dadosgovbr.github.io/kit/
org_name: dadosgovbr

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false